### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by leomaury** [bioimageit/bioimageit#29]
Convert the website https://bioimageit.github.io/#/ from Vue.js to WordPress or HTML/CSS.

**Comment by leomaury** [comment]
Impossible to update the website 

![image](https://user-images.githubusercontent.com/42140279/225270385-9e1fa9df-f95c-442d-9472-70d02e20fbd7.png)

**Comment by KevinFournier** [comment]
The problem was the version of VueJS used to build the website.
Many dependency was deprecated, had dependeces issues and/or had security hazard. Resulting in failde build without manual modifications.

Vue was updated from Vue 2 to Vue 3, keeping a Vue 2 compatibility patch for bootstrap to keep working.
